apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment   # Name of the deployment
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-container   # Name of the container (different from the deployment name)
        image: henrykum23/netflix:latest
        ports:
        - containerPort: 80

